name: greek_tools
description: A Dart library for manipulating Greek text - mainly transforming between Latin and Greek character sets.
version: 1.0.1
homepage: https://github.com/nearchos/greek_tools
repository: https://github.com/nearchos/greek_tools

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
